AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Environment:              {Type: String, Default: "test", AllowedValues: ["prod", "test", "dev"]}
  Domain:                   {Type: String, Default: "litterapp.net"}
  EmailAddress:             {Type: String, Default: "info@litterapp.net"}

Resources:
  SESIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      DkimAttributes: 
          SigningEnabled: "true"
      EmailIdentity: !Ref Domain
      FeedbackAttributes: 
          EmailForwardingEnabled: "false"
      MailFromAttributes: 
          BehaviorOnMxFailure: USE_DEFAULT_VALUE
          MailFromDomain: !Sub "mail.${Domain}"

  # SESDNSRecords:
  #   Type: AWS::Route53::RecordSetGroup
  #   Properties:
  #     HostedZoneName: !Ref Domain
  #     RecordSets:
  #       - Name: !Ref SESIdentity
  #         Type: "TXT"
  #         TTL: "300"
  #         ResourceRecords:
  #           - "v=spf1 include:amazonses.com ~all"

  SESConfigurationSet:
    Type: AWS::SES::ConfigurationSet
    Properties:
      Name: !Sub "${Environment}-ConfigurationSet"


  # SESConfigurationSetEventDestination:
  #   Type: "AWS::SES::ConfigurationSetEventDestination"
  #   Properties:
  #     ConfigurationSetName: !Ref SESConfigurationSet
  #     EventDestination:
  #       Name: !Sub "${Domain}-EventDestination"
  #       Enabled: true
  #       MatchingEventTypes:
  #         - "send"
  #         - "reject"
  #         - "bounce"
  #         - "complaint"
  #         - "delivery"
  #         - "open"
  #         - "click"
  #       SNSDestination:
  #         TopicARN: "arn:aws:sns:REGION:ACCOUNT_ID:MyTopic" # Replace with your SNS topic ARN

  SESReceiptRuleSet:
    Type: "AWS::SES::ReceiptRuleSet"
    Properties:
      RuleSetName: !Sub "${Domain}-RuleSet"

  # SESReceiptRule:
  #   Type: "AWS::SES::ReceiptRule"
  #   Properties:
  #     RuleSetName: !Ref SESReceiptRuleSet
  #     Rule:
  #       Name: !Sub "${Domain}-ReceiptRule"
  #       Enabled: true
  #       TlsPolicy: "Optional"
  #       Recipients:
  #         - !Ref EmailAddress
  #       Actions:
  #         - S3Action:
  #             BucketName: "my-bucket"
  #             ObjectKeyPrefix: "emails/"
  #         - StopAction: {}

  # SESReceiptRuleSetLambdaFunction:
  #   Type: "AWS::Lambda::Function"
  #   Properties:
  #     Code:
  #       S3Bucket: "lambda-function-bucket"
  #       S3Key: "lambda-function-key"
  #     Handler: "index.handler"
  #     Role: "arn:aws:iam::ACCOUNT_ID:role/lambda-role"
  #     Runtime: "nodejs12.x"
